##
 # Helm values for 'ironbark-app-of-apps' chart.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

applications:
  - name: ironbark-podinfo
    chart:
      # Chart name as found in the OCI registry.
      # This will be appended to the `config.spec.source.ociUrl`.
      name: stefanprodan/charts/podinfo
      # Chart version to deploy.
      # IMPORTANT: Keep this aligned with `resources/packages/mirror/bsl-ironbark-podinfo/zarf.yaml`.
      targetRevision: 6.10.1

    values:
      # Path to the Helm values YAML file to use.
      path: values/ironbark-podinfo/values-blue.yaml
      # Example alternative:
      #path: values/podinfo/values-green.yaml

      # Version of the repo to checkout.
      targetRevision: HEAD

      # Use a custom repo instead of default (`config.spec.source.valuesRepoUrl`).
      #repo: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/helm-chart-values.git

config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      # URL of OCI registry. NOTE: Do *not* include 'oci://' prefix.
      ociUrl: internal-tls-proxy.bsl-ironbark-internal-tls-proxy.svc.cluster.local
      # TODO: Switch to internal once forcing HTTP works.
      #ociUrl: zarf-docker-registry.zarf.svc.cluster.local:5000

      # Default git repository containing Helm values YAML files for the deployed charts.
      valuesRepoURL: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/ironbark-argocd-app-of-apps.git
