##
 # Zarf package.
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

# NOTE: The `images` block is generated via: `zarf -l debug prepare find-images'.

kind: ZarfPackageConfig
metadata:
  name: bsl-ironbark
  version: 0.0.0
  description: BSL ironbark services in Kubernetes

components:
  - name: argocd-helm-chart
    required: true
    charts:
      - name: argo-cd
        version: 9.0.5
        namespace: bsl-ironbark-argocd
        url: https://argoproj.github.io/argo-helm
        releaseName: argocd
        valuesFiles:
          - argocd-helm-chart/values.yaml
    images:
      - docker.io/library/redis:7.2.11-alpine
      - quay.io/argoproj/argocd:v3.1.9
      # Cosign artifacts for images - argocd-helm-chart
      - quay.io/argoproj/argocd:sha256-9c33285c0b86a66e9cf9fcafc448e48e0ab7c4678b20b3723556bb6cce8ea0b9.sig
      - quay.io/argoproj/argocd:sha256-9c33285c0b86a66e9cf9fcafc448e48e0ab7c4678b20b3723556bb6cce8ea0b9.att
  - name: eso-chart
    required: true
    charts:
      - name: external-secrets
        version: 0.20.3
        namespace: bsl-ironbark-eso
        url: https://charts.external-secrets.io
        #valuesFiles:
          #- eso-chart/values.yaml
    images:
      - oci.external-secrets.io/external-secrets/external-secrets:v0.20.3
      # Cosign artifacts for images - eso-chart
      - oci.external-secrets.io/external-secrets/external-secrets:sha256-1d2acb58ac792110ed01e0ece4880ab48b029ee5b1d3c1c22932d82781badfed.sig
      - oci.external-secrets.io/external-secrets/external-secrets:sha256-1d2acb58ac792110ed01e0ece4880ab48b029ee5b1d3c1c22932d82781badfed.att
  - name: sync-zarf-secrets
    description: |
      Ensures the zarf secrets for registry/repo access are available in any namespaces created outside of Zarf.
    required: true
    manifests:
      - name: sync-zarf-secrets
        files:
          - sync-zarf-secrets/manifest.yaml
  - name: internal-tls-proxy
    description: |
      Expose internal HTTP services through a HTTPS connection.
    required: true
    manifests:
      - name: internal-tls-proxy
        namespace: bsl-ironbark-internal-tls-proxy
        files:
          - internal-tls-proxy/manifests.yaml
    images:
      # IMPORTANT: Keep this aligned with `internal-tls-proxy/manifests.yaml`.
      - caddy:2.10-alpine
