{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: bsl-ironbark-argocd
  labels:
    zarf.dev/agent: ignore
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace | default .name | quote }}
    server: {{ $config.spec.destination.server | quote }}
  project: default
  sources:
    # The OCI registry to source the chart from.
    - repoURL: {{ $config.spec.source.ociUrl }}
      targetRevision: {{ .chart.targetRevision }}
      chart:  {{ .chart.name }}
      helm:
        # $values is replaced by the repository defined in the sources item below.
        valueFiles:
        - $values/{{ .values.path }}
        {{- if .values.fileParameters }}
        # File parameters (equivalent to helm --set-file).
        fileParameters:
        {{- range .values.fileParameters }}
        - name: {{ .name }}
          path: $values/{{ .path }}
        {{- end }}
        {{- end }}

    # Git repository to source the Helm values YAML from.
    # Defined as a separate source to allow for different `targetRevision` to be used.
    - repoURL: {{ .values.repo | default $config.spec.source.valuesRepoURL }}
      targetRevision: {{ .values.targetRevision }}
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
{{ end -}}
